blank_issues_enabled: false
contact_links:
  - name: Questions and help
    url: https://github.com/uidb-dev/jops-core/discussions
    about: Ask usage questions in Discussions
  - name: Documentation
    url: https://cdn.ui-db.com
    about: API reference and guides
